# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # Main container image
      - image: circleci/node:9-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.6.3-jessie-ram

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - node-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - node-dependencies-

      - run:
          name: Install node dependencies and perform snyk vunerabilities checker
          command: npm install

      - run:
          name: Install MongoDB on main container
          command: sudo apt-get update && sudo apt-get install mongodb

      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run flow type checks
          command: npm run flow

      - run:
          name: Run tests and send coverage report to codecov
          command: npm run codecov-report
